version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "wxx9248"
      - "Msuzuki-0112"
    commit-message:
      prefix: "Dependency Updates"
    reviewers:
      - "wxx9248"
      - "Msuzuki-0112"
      
