name: build
on:
  push:
    branches:
      - master
      - 3-create-github-action-scripts-for-automatic-release
  workflow_dispatch: null

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Python and pip
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: "pip"
      - name: Installing Python requirements
        run: |
          pip install -r requirements.txt
      - name: Generating distributable
        run: |
          pyinstaller -F main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'pickle-rush-windows-amd64'
          path: dist/main.exe
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Python and pip
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: "pip"
      - name: Installing Python requirements
        run: |
          pip install -r requirements.txt
      - name: Generating distributable
        run: |
          pyinstaller -F main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'pickle-rush-linux-amd64'
          path: |
            dist/main
            config.json
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Python and pip
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: "pip"
      - name: Installing Python requirements
        run: |
          pip install -r requirements.txt
      - name: Generating distributable
        run: |
          pyinstaller -F main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'pickle-rush-macos-amd64'
          path: dist/main
